[tool.poetry]
name = "poetry-githooks"
version = "0.1.3"
description = ""
authors = ["Thomas Thiebaud <thiebaud.tom@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[tool.poetry.scripts]
githooks = "poetry_githooks:cli"

[tool.githooks]
pre-commit = "black ."

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
